import type { Template } from "@/lib/contracts";
import { buildTemplate, type Palette } from "./blueprint";

// The template library, as the discovery mockup draws it: twelve designs, each led by a
// real photograph rather than the code-drawn motif (the motif stays as the fallback for a
// design that ships no image — see blueprint.ts). One blueprint per design; the generator
// still emits the markup, stylesheet and content schema together, so there is zero
// per-template UI and the gallery tile is parsed from the very files it advertises.
//
// Photographs are hosted on Unsplash (Unsplash licence — free to use, no attribution
// required) and sit in the hero.image slot, which is an editable content field: a site
// owner swaps in their own photo without touching the template.

const PHOTO = "?w=1600&q=70&auto=format&fit=crop";
const img = (id: string): string => `https://images.unsplash.com/${id}${PHOTO}`;

const LIGHT = { bg: "#ffffff", ink: "#171717", muted: "#6b7280", panel: "#f4f4f5", rule: "#e5e7eb" };
const DARK = { bg: "#0b0b0f", ink: "#fafafa", muted: "#a1a1aa", panel: "#18181b", rule: "#27272a" };
const light = (accent: string): Palette => ({ ...LIGHT, accent });
const dark = (accent: string): Palette => ({ ...DARK, accent });

const source = (id: string): string => `https://github.com/pagecraft/templates/tree/main/${id}`;

export const DESIGNS: Template[] = [
    buildTemplate({
        id: "gym",
        name: "Gym",
        description: "A high-energy fitness landing page — bold hero, class schedule and a join prompt.",
        category: "fitness",
        tags: ["fitness", "gym", "dark", "bold"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("gym"),
        layout: "full-bleed",
        palette: dark("#ef4444"),
        nav: ["Classes", "Trainers", "Pricing", "Contact"],
        hero: {
            headline: "Stronger every day.",
            subhead: "Train hard, stay focused, and be your best. Your first session is on us.",
            cta: "Join now",
        },
        heroImage: { src: img("photo-1534438327276-14e5300c3a48"), alt: "Athlete lifting a dumbbell in a gym" },
        sections: [
            {
                key: "classes",
                label: "Classes",
                kind: "cards",
                heading: "Find your session",
                body: "Strength, conditioning and mobility — coached in small groups, six days a week.",
                cards: [
                    { title: "Strength", body: "Barbell fundamentals and progressive overload, scaled to you." },
                    { title: "Conditioning", body: "Short, hard intervals that leave you fitter, not wrecked." },
                    { title: "Mobility", body: "Move well before you move heavy. The unglamorous work that lasts." },
                ],
            },
            {
                key: "join",
                label: "Join",
                kind: "form",
                heading: "Start this week",
                body: "Leave your email and we will book your free first session.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "portfolio",
        name: "Portfolio",
        description: "A clean personal portfolio — a bold hero, selected work and a way to reach you.",
        category: "portfolio",
        tags: ["portfolio", "minimal", "light", "personal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("portfolio"),
        layout: "split",
        palette: light("#4f46e5"),
        nav: ["Work", "About", "Contact"],
        hero: {
            headline: "Hi, I'm Alex — a designer who ships.",
            subhead: "A product designer based in Bangalore, building interfaces people actually enjoy using.",
            cta: "View work",
        },
        heroImage: { src: img("photo-1499750310107-5fef28a66643"), alt: "A tidy desk with a laptop and notebook" },
        sections: [
            {
                key: "work",
                label: "Projects",
                kind: "cards",
                heading: "Selected work",
                body: "A short list beats a long one. Three pieces that show how I think.",
                cards: [
                    { title: "Project one", body: "What it was, what you did, and what changed because of it." },
                    { title: "Project two", body: "One line on the problem, one on your part in solving it." },
                    { title: "Project three", body: "Keep it concrete. Numbers if you have them." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Let's talk",
                body: "Have a project in mind? Drop your email and I'll get back to you.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "restaurant",
        name: "Restaurant",
        description: "A warm, dark restaurant site — a mood-setting hero, the menu and a booking prompt.",
        category: "food",
        tags: ["food", "restaurant", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("restaurant"),
        layout: "full-bleed",
        palette: dark("#f59e0b"),
        nav: ["Menu", "Hours", "Find us"],
        hero: {
            headline: "Good food. Good mood.",
            subhead: "Wood-fired plates and slow pours, on the corner. Open Wednesday to Sunday, six until late.",
            cta: "Book a table",
        },
        heroImage: { src: img("photo-1414235077428-338989a2e8c0"), alt: "A warmly lit restaurant dining room" },
        sections: [
            {
                key: "menu",
                label: "Menu",
                kind: "cards",
                heading: "On the menu",
                body: "A short card that changes with the season — here is what is on this week.",
                cards: [
                    { title: "To start", body: "Small plates made to share, while you decide on the rest." },
                    { title: "Mains", body: "From the fire: a handful of dishes, each done properly." },
                    { title: "Sweet", body: "One or two things worth leaving room for." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Reserve a table",
                body: "Leave your email and we'll confirm your booking.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "blog",
        name: "Blog",
        description: "A quiet, readable blog — a calm hero, a list of posts and a way to subscribe.",
        category: "blog",
        tags: ["blog", "editorial", "light", "reading"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("blog"),
        layout: "split",
        palette: light("#0ea5e9"),
        nav: ["Latest", "Archive", "About"],
        hero: {
            headline: "Stories that inspire.",
            subhead: "Thoughts, ideas and everything in between — roughly fortnightly, never automated.",
            cta: "Read latest",
        },
        heroImage: { src: img("photo-1486312338219-ce68d2c6f44d"), alt: "A laptop open on a bright desk" },
        sections: [
            {
                key: "posts",
                label: "Posts",
                kind: "cards",
                heading: "Latest posts",
                body: "The most recent writing, newest first.",
                cards: [
                    { title: "A first post", body: "Set the tone. What this blog is about and who it is for." },
                    { title: "A second post", body: "A single idea, followed all the way through." },
                    { title: "A third post", body: "Short is fine. Say the thing and stop." },
                ],
            },
            {
                key: "subscribe",
                label: "Subscribe",
                kind: "form",
                heading: "Never miss a post",
                body: "Get new writing in your inbox. No spam, unsubscribe any time.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "resume",
        name: "Resume",
        description: "A single-page resume — a personal hero, your experience and how to reach you.",
        category: "resume",
        tags: ["resume", "cv", "light", "personal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("resume"),
        layout: "showcase",
        palette: light("#7c3aed"),
        nav: ["Experience", "Skills", "Contact"],
        hero: {
            headline: "Hello, I'm Riya Sharma.",
            subhead: "A product manager who ships thoughtful things — here's my work, and how to reach me.",
            cta: "Download CV",
        },
        heroImage: { src: img("photo-1521737604893-d14cc237f11d"), alt: "A professional portrait" },
        sections: [
            {
                key: "experience",
                label: "Experience",
                kind: "cards",
                heading: "Experience",
                body: "The roles that shaped how I work, most recent first.",
                cards: [
                    { title: "Product Manager", body: "What you owned, and the outcome you're proud of." },
                    { title: "Associate PM", body: "One line on scope, one on impact." },
                    { title: "Earlier", body: "Where you started and what you learned there." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Get in touch",
                body: "Hiring, or just want to talk? Leave your email.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "photography",
        name: "Photography",
        description: "A full-bleed photography portfolio — an immersive hero, a gallery and a booking prompt.",
        category: "photography",
        tags: ["photography", "gallery", "dark", "visual"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("photography"),
        layout: "full-bleed",
        palette: dark("#38bdf8"),
        nav: ["Portfolio", "About", "Contact"],
        hero: {
            headline: "Capturing moments, creating stories.",
            subhead: "Landscape and portrait work from wherever the light is worth chasing.",
            cta: "View gallery",
        },
        heroImage: { src: img("photo-1452587925148-ce544e77e70d"), alt: "A camera resting against a mountain backdrop" },
        sections: [
            {
                key: "gallery",
                label: "Gallery",
                kind: "cards",
                heading: "Recent work",
                body: "A few frames from recent shoots — the rest lives in the full gallery.",
                cards: [
                    { title: "Landscapes", body: "Wide, quiet places, shot at the edges of the day." },
                    { title: "Portraits", body: "People, at ease, in their own light." },
                    { title: "Events", body: "The moments that pass too fast to notice live." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a shoot",
                body: "Tell me what you have in mind — leave your email to start.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "architecture",
        name: "Architecture",
        description: "A confident architecture studio site — a strong hero, projects and a contact prompt.",
        category: "architecture",
        tags: ["architecture", "studio", "light", "minimal"],
        tier: "signature",
        license: "MIT",
        sourceUrl: source("architecture"),
        layout: "split",
        palette: light("#0f766e"),
        nav: ["Projects", "Studio", "Services", "Contact"],
        hero: {
            headline: "Designing spaces that inspire.",
            subhead: "A studio for buildings that feel inevitable — considered, durable, quietly bold.",
            cta: "View projects",
        },
        heroImage: { src: img("photo-1487958449943-2429e8be8625"), alt: "A modern building facade" },
        sections: [
            {
                key: "projects",
                label: "Projects",
                kind: "cards",
                heading: "Selected projects",
                body: "A few recent commissions across homes, workplaces and public space.",
                cards: [
                    { title: "Residential", body: "Homes built around how people actually live." },
                    { title: "Commercial", body: "Workplaces that earn their footprint." },
                    { title: "Public", body: "Spaces that belong to everyone who uses them." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Start a project",
                body: "Have a site or a brief? Leave your email and we'll be in touch.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "school",
        name: "School",
        description: "A welcoming school site — a bright hero, programmes and an admissions prompt.",
        category: "education",
        tags: ["education", "school", "light", "friendly"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("school"),
        layout: "split",
        palette: light("#2563eb"),
        nav: ["Programmes", "Admissions", "Campus", "Contact"],
        hero: {
            headline: "Bright minds. Better tomorrow.",
            subhead: "Empowering students to learn, grow and lead — enrolment is open for the new term.",
            cta: "Apply now",
        },
        heroImage: { src: img("photo-1509062522246-3755977927d7"), alt: "Students in a bright classroom" },
        sections: [
            {
                key: "programmes",
                label: "Programmes",
                kind: "cards",
                heading: "Our programmes",
                body: "A rounded education, from the early years through to graduation.",
                cards: [
                    { title: "Primary", body: "Curiosity first — the habits that make learning stick." },
                    { title: "Secondary", body: "Depth and choice, with real support behind it." },
                    { title: "Beyond", body: "College counselling and the skills that outlast exams." },
                ],
            },
            {
                key: "admissions",
                label: "Admissions",
                kind: "form",
                heading: "Enquire about a place",
                body: "Leave your email and our admissions team will reach out.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "travel",
        name: "Travel",
        description: "An inviting travel site — a centred hero, featured trips and a newsletter prompt.",
        category: "travel",
        tags: ["travel", "adventure", "light", "centered"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("travel"),
        layout: "centered",
        palette: light("#059669"),
        nav: ["Trips", "Guides", "About"],
        hero: {
            headline: "Explore. Dream. Discover.",
            subhead: "Journeys to the most beautiful places on Earth, planned so you can just go.",
            cta: "Explore trips",
        },
        heroImage: { src: img("photo-1476514525535-07fb3b4ae5f1"), alt: "A mountain lake at dawn" },
        sections: [
            {
                key: "trips",
                label: "Trips",
                kind: "cards",
                heading: "Featured trips",
                body: "Small groups, real places, and none of the logistics on you.",
                cards: [
                    { title: "Mountains", body: "High trails and quiet mornings, at an honest pace." },
                    { title: "Coast", body: "Slow days by the water, with room to do nothing." },
                    { title: "Cities", body: "The good parts, minus the tourist traps." },
                ],
            },
            {
                key: "newsletter",
                label: "Newsletter",
                kind: "form",
                heading: "Get trip ideas",
                body: "New routes and dates in your inbox. Leave your email.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "agency",
        name: "Agency",
        description: "A bold creative agency showcase — a statement hero, services and selected work.",
        category: "agency",
        tags: ["agency", "creative", "dark", "bold"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("agency"),
        layout: "full-bleed",
        palette: dark("#ec4899"),
        nav: ["Work", "Services", "Studio", "Contact"],
        hero: {
            headline: "We build brands that connect.",
            subhead: "Strategy, design and development for founders who would rather be remembered than noticed.",
            cta: "See the work",
        },
        heroImage: { src: img("photo-1552664730-d307ca884978"), alt: "A team collaborating around a table" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we do",
                body: "Three things, done properly, from first idea to shipped product.",
                cards: [
                    { title: "Strategy", body: "The positioning and story before a single pixel." },
                    { title: "Design", body: "Brand and product design that carries the idea." },
                    { title: "Build", body: "Fast, durable sites and apps that ship on time." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Start a project",
                body: "Tell us what you're building — leave your email to begin.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "consultant",
        name: "Consultant",
        description: "A trustworthy consulting site — a clear hero, services and a booking prompt.",
        category: "business",
        tags: ["business", "consulting", "light", "professional"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("consultant"),
        layout: "split",
        palette: light("#1d4ed8"),
        nav: ["Services", "About", "Case studies", "Contact"],
        hero: {
            headline: "Solutions that drive growth.",
            subhead: "Business consulting for modern companies — clear advice, measured against results.",
            cta: "Book a call",
        },
        heroImage: { src: img("photo-1507003211169-0a1dd7228f2d"), alt: "A professional in a suit" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How we help",
                body: "Focused engagements that move a real number, not a slide deck.",
                cards: [
                    { title: "Strategy", body: "Where to play and how to win, made concrete." },
                    { title: "Operations", body: "Take the friction out of how the work gets done." },
                    { title: "Growth", body: "Repeatable ways to reach and keep customers." },
                ],
            },
            {
                key: "call",
                label: "Call",
                kind: "form",
                heading: "Book a call",
                body: "Leave your email and we'll find a time that works.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "event",
        name: "Event",
        description: "A one-page event site — a lively hero, the line-up and a registration prompt.",
        category: "event",
        tags: ["event", "conference", "dark", "vibrant"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("event"),
        layout: "full-bleed",
        palette: dark("#a855f7"),
        nav: ["Line-up", "Venue", "Tickets"],
        hero: {
            headline: "An event that stays with you.",
            subhead: "One day, one room, and a line-up worth clearing your calendar for. Plan, celebrate, remember.",
            cta: "Get tickets",
        },
        heroImage: { src: img("photo-1470229722913-7c0e2dbbafd3"), alt: "A crowd at a concert with stage lights" },
        sections: [
            {
                key: "lineup",
                label: "Line-up",
                kind: "cards",
                heading: "The line-up",
                body: "The people worth listening to — full schedule on the day.",
                cards: [
                    { title: "Keynotes", body: "The talks that set the tone for the day." },
                    { title: "Sessions", body: "Hands-on, practical, and short enough to hold attention." },
                    { title: "After hours", body: "The part where the real conversations happen." },
                ],
            },
            {
                key: "register",
                label: "Register",
                kind: "form",
                heading: "Register now",
                body: "Save your seat — leave your email and we'll send your ticket.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    // Template 13 (D6). It is a storefront because that was the library's one hole: the
    // describe screen has offered an "E-commerce" card since D3, and until now the library
    // shipped no design in the `store` bucket, so pressing it quietly fell through to the
    // whole library. A card that leads to the right kind of design is worth more than a
    // thirteenth design of a kind we already had.
    buildTemplate({
        id: "shop",
        name: "Shop",
        description: "A small online shop — a product-led hero, what's in stock and a way to order.",
        category: "store",
        tags: ["store", "shop", "light", "warm"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("shop"),
        layout: "showcase",
        palette: light("#0f766e"),
        nav: ["Shop", "About", "Delivery", "Contact"],
        hero: {
            headline: "Made in small batches.",
            subhead: "Everything here is made by hand, in short runs, and sent out the week you order it.",
            cta: "Shop the range",
        },
        heroImage: {
            src: img("photo-1441986300917-64674bd600d8"),
            alt: "A shelf of ceramics in a small shop",
        },
        sections: [
            {
                key: "range",
                label: "Products",
                kind: "cards",
                heading: "In stock now",
                body: "A short range, restocked as it sells. When something is gone it is genuinely gone.",
                cards: [
                    { title: "Everyday mug", body: "Thrown by hand, glazed in slate. Holds a proper amount of tea." },
                    { title: "Serving bowl", body: "Wide, shallow and heavy enough to stay put on a full table." },
                    { title: "Small vase", body: "For one stem or a handful of whatever is in season." },
                ],
            },
            {
                key: "delivery",
                label: "Delivery",
                kind: "prose",
                heading: "Delivery and returns",
                body: "Orders go out within three working days. If something arrives damaged, tell us and we replace it.",
            },
            {
                key: "order",
                label: "Order",
                kind: "form",
                heading: "Order or ask",
                body: "Leave your email and we'll get back to you about stock, sizes or a custom piece.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
];
