import type { Template } from "@/lib/contracts";
import { buildTemplate, type Palette } from "./blueprint";

// The template library, as the discovery mockups draw it: fifty-one designs across four
// batches (1-12, 13-24, 25-36, 37-51), each led by a real photograph rather than the code-drawn
// motif (the motif stays as the fallback for a design that ships no image — see
// blueprint.ts). One blueprint per design; the generator
// still emits the markup, stylesheet and content schema together, so there is zero
// per-template UI and the gallery tile is parsed from the very files it advertises.
//
// Photographs are hosted on Unsplash (Unsplash licence — free to use, no attribution
// required) and sit in the hero.image slot, which is an editable content field: a site
// owner swaps in their own photo without touching the template.

const PHOTO = "?w=1600&q=70&auto=format&fit=crop";
const img = (id: string): string => `https://images.unsplash.com/${id}${PHOTO}`;

const LIGHT = { bg: "#ffffff", ink: "#171717", muted: "#6b7280", panel: "#f4f4f5", rule: "#e5e7eb" };
const DARK = { bg: "#0b0b0f", ink: "#fafafa", muted: "#a1a1aa", panel: "#18181b", rule: "#27272a" };
const light = (accent: string): Palette => ({ ...LIGHT, accent });
const dark = (accent: string): Palette => ({ ...DARK, accent });

const source = (id: string): string => `https://github.com/pagecraft/templates/tree/main/${id}`;

export const DESIGNS: Template[] = [
    buildTemplate({
        id: "gym",
        name: "Gym",
        description: "A high-energy fitness landing page — bold hero, class schedule and a join prompt.",
        category: "fitness",
        tags: ["fitness", "gym", "dark", "bold"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("gym"),
        layout: "full-bleed",
        palette: dark("#ef4444"),
        nav: ["Classes", "Trainers", "Pricing", "Contact"],
        hero: {
            headline: "Stronger every day.",
            subhead: "Train hard, stay focused, and be your best. Your first session is on us.",
            cta: "Join now",
        },
        heroImage: { src: img("photo-1534438327276-14e5300c3a48"), alt: "Athlete lifting a dumbbell in a gym" },
        sections: [
            {
                key: "classes",
                label: "Classes",
                kind: "cards",
                heading: "Find your session",
                body: "Strength, conditioning and mobility — coached in small groups, six days a week.",
                cards: [
                    { title: "Strength", body: "Barbell fundamentals and progressive overload, scaled to you." },
                    { title: "Conditioning", body: "Short, hard intervals that leave you fitter, not wrecked." },
                    { title: "Mobility", body: "Move well before you move heavy. The unglamorous work that lasts." },
                ],
            },
            {
                key: "join",
                label: "Join",
                kind: "form",
                heading: "Start this week",
                body: "Leave your email and we will book your free first session.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "portfolio",
        name: "Portfolio",
        description: "A clean personal portfolio — a bold hero, selected work and a way to reach you.",
        category: "portfolio",
        tags: ["portfolio", "minimal", "light", "personal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("portfolio"),
        layout: "split",
        palette: light("#4f46e5"),
        nav: ["Work", "About", "Contact"],
        hero: {
            headline: "Hi, I'm Alex — a designer who ships.",
            subhead: "A product designer based in Bangalore, building interfaces people actually enjoy using.",
            cta: "View work",
        },
        heroImage: { src: img("photo-1499750310107-5fef28a66643"), alt: "A tidy desk with a laptop and notebook" },
        sections: [
            {
                key: "work",
                label: "Projects",
                kind: "cards",
                heading: "Selected work",
                body: "A short list beats a long one. Three pieces that show how I think.",
                cards: [
                    { title: "Project one", body: "What it was, what you did, and what changed because of it." },
                    { title: "Project two", body: "One line on the problem, one on your part in solving it." },
                    { title: "Project three", body: "Keep it concrete. Numbers if you have them." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Let's talk",
                body: "Have a project in mind? Drop your email and I'll get back to you.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "restaurant",
        name: "Restaurant",
        description: "A warm, dark restaurant site — a mood-setting hero, the menu and a booking prompt.",
        category: "food",
        tags: ["food", "restaurant", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("restaurant"),
        layout: "full-bleed",
        palette: dark("#f59e0b"),
        nav: ["Menu", "Hours", "Find us"],
        hero: {
            headline: "Good food. Good mood.",
            subhead: "Wood-fired plates and slow pours, on the corner. Open Wednesday to Sunday, six until late.",
            cta: "Book a table",
        },
        heroImage: { src: img("photo-1414235077428-338989a2e8c0"), alt: "A warmly lit restaurant dining room" },
        sections: [
            {
                key: "menu",
                label: "Menu",
                kind: "cards",
                heading: "On the menu",
                body: "A short card that changes with the season — here is what is on this week.",
                cards: [
                    { title: "To start", body: "Small plates made to share, while you decide on the rest." },
                    { title: "Mains", body: "From the fire: a handful of dishes, each done properly." },
                    { title: "Sweet", body: "One or two things worth leaving room for." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Reserve a table",
                body: "Leave your email and we'll confirm your booking.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "blog",
        name: "Blog",
        description: "A quiet, readable blog — a calm hero, a list of posts and a way to subscribe.",
        category: "blog",
        tags: ["blog", "editorial", "light", "reading"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("blog"),
        layout: "split",
        palette: light("#0ea5e9"),
        nav: ["Latest", "Archive", "About"],
        hero: {
            headline: "Stories that inspire.",
            subhead: "Thoughts, ideas and everything in between — roughly fortnightly, never automated.",
            cta: "Read latest",
        },
        heroImage: { src: img("photo-1486312338219-ce68d2c6f44d"), alt: "A laptop open on a bright desk" },
        sections: [
            {
                key: "posts",
                label: "Posts",
                kind: "cards",
                heading: "Latest posts",
                body: "The most recent writing, newest first.",
                cards: [
                    { title: "A first post", body: "Set the tone. What this blog is about and who it is for." },
                    { title: "A second post", body: "A single idea, followed all the way through." },
                    { title: "A third post", body: "Short is fine. Say the thing and stop." },
                ],
            },
            {
                key: "subscribe",
                label: "Subscribe",
                kind: "form",
                heading: "Never miss a post",
                body: "Get new writing in your inbox. No spam, unsubscribe any time.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "resume",
        name: "Resume",
        description: "A single-page resume — a personal hero, your experience and how to reach you.",
        category: "resume",
        tags: ["resume", "cv", "light", "personal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("resume"),
        layout: "showcase",
        palette: light("#7c3aed"),
        nav: ["Experience", "Skills", "Contact"],
        hero: {
            headline: "Hello, I'm Riya Sharma.",
            subhead: "A product manager who ships thoughtful things — here's my work, and how to reach me.",
            cta: "Download CV",
        },
        heroImage: { src: img("photo-1521737604893-d14cc237f11d"), alt: "A professional portrait" },
        sections: [
            {
                key: "experience",
                label: "Experience",
                kind: "cards",
                heading: "Experience",
                body: "The roles that shaped how I work, most recent first.",
                cards: [
                    { title: "Product Manager", body: "What you owned, and the outcome you're proud of." },
                    { title: "Associate PM", body: "One line on scope, one on impact." },
                    { title: "Earlier", body: "Where you started and what you learned there." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Get in touch",
                body: "Hiring, or just want to talk? Leave your email.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "photography",
        name: "Photography",
        description: "A full-bleed photography portfolio — an immersive hero, a gallery and a booking prompt.",
        category: "photography",
        tags: ["photography", "gallery", "dark", "visual"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("photography"),
        layout: "full-bleed",
        palette: dark("#38bdf8"),
        nav: ["Portfolio", "About", "Contact"],
        hero: {
            headline: "Capturing moments, creating stories.",
            subhead: "Landscape and portrait work from wherever the light is worth chasing.",
            cta: "View gallery",
        },
        heroImage: { src: img("photo-1452587925148-ce544e77e70d"), alt: "A camera resting against a mountain backdrop" },
        sections: [
            {
                key: "gallery",
                label: "Gallery",
                kind: "cards",
                heading: "Recent work",
                body: "A few frames from recent shoots — the rest lives in the full gallery.",
                cards: [
                    { title: "Landscapes", body: "Wide, quiet places, shot at the edges of the day." },
                    { title: "Portraits", body: "People, at ease, in their own light." },
                    { title: "Events", body: "The moments that pass too fast to notice live." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a shoot",
                body: "Tell me what you have in mind — leave your email to start.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "architecture",
        name: "Architecture",
        description: "A confident architecture studio site — a strong hero, projects and a contact prompt.",
        category: "architecture",
        tags: ["architecture", "studio", "light", "minimal"],
        tier: "signature",
        license: "MIT",
        sourceUrl: source("architecture"),
        layout: "split",
        palette: light("#0f766e"),
        nav: ["Projects", "Studio", "Services", "Contact"],
        hero: {
            headline: "Designing spaces that inspire.",
            subhead: "A studio for buildings that feel inevitable — considered, durable, quietly bold.",
            cta: "View projects",
        },
        heroImage: { src: img("photo-1487958449943-2429e8be8625"), alt: "A modern building facade" },
        sections: [
            {
                key: "projects",
                label: "Projects",
                kind: "cards",
                heading: "Selected projects",
                body: "A few recent commissions across homes, workplaces and public space.",
                cards: [
                    { title: "Residential", body: "Homes built around how people actually live." },
                    { title: "Commercial", body: "Workplaces that earn their footprint." },
                    { title: "Public", body: "Spaces that belong to everyone who uses them." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Start a project",
                body: "Have a site or a brief? Leave your email and we'll be in touch.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "school",
        name: "School",
        description: "A welcoming school site — a bright hero, programmes and an admissions prompt.",
        category: "education",
        tags: ["education", "school", "light", "friendly"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("school"),
        layout: "split",
        palette: light("#2563eb"),
        nav: ["Programmes", "Admissions", "Campus", "Contact"],
        hero: {
            headline: "Bright minds. Better tomorrow.",
            subhead: "Empowering students to learn, grow and lead — enrolment is open for the new term.",
            cta: "Apply now",
        },
        heroImage: { src: img("photo-1509062522246-3755977927d7"), alt: "Students in a bright classroom" },
        sections: [
            {
                key: "programmes",
                label: "Programmes",
                kind: "cards",
                heading: "Our programmes",
                body: "A rounded education, from the early years through to graduation.",
                cards: [
                    { title: "Primary", body: "Curiosity first — the habits that make learning stick." },
                    { title: "Secondary", body: "Depth and choice, with real support behind it." },
                    { title: "Beyond", body: "College counselling and the skills that outlast exams." },
                ],
            },
            {
                key: "admissions",
                label: "Admissions",
                kind: "form",
                heading: "Enquire about a place",
                body: "Leave your email and our admissions team will reach out.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "travel",
        name: "Travel",
        description: "An inviting travel site — a centred hero, featured trips and a newsletter prompt.",
        category: "travel",
        tags: ["travel", "adventure", "light", "centered"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("travel"),
        layout: "centered",
        palette: light("#059669"),
        nav: ["Trips", "Guides", "About"],
        hero: {
            headline: "Explore. Dream. Discover.",
            subhead: "Journeys to the most beautiful places on Earth, planned so you can just go.",
            cta: "Explore trips",
        },
        heroImage: { src: img("photo-1476514525535-07fb3b4ae5f1"), alt: "A mountain lake at dawn" },
        sections: [
            {
                key: "trips",
                label: "Trips",
                kind: "cards",
                heading: "Featured trips",
                body: "Small groups, real places, and none of the logistics on you.",
                cards: [
                    { title: "Mountains", body: "High trails and quiet mornings, at an honest pace." },
                    { title: "Coast", body: "Slow days by the water, with room to do nothing." },
                    { title: "Cities", body: "The good parts, minus the tourist traps." },
                ],
            },
            {
                key: "newsletter",
                label: "Newsletter",
                kind: "form",
                heading: "Get trip ideas",
                body: "New routes and dates in your inbox. Leave your email.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "agency",
        name: "Agency",
        description: "A bold creative agency showcase — a statement hero, services and selected work.",
        category: "agency",
        tags: ["agency", "creative", "dark", "bold"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("agency"),
        layout: "full-bleed",
        palette: dark("#ec4899"),
        nav: ["Work", "Services", "Studio", "Contact"],
        hero: {
            headline: "We build brands that connect.",
            subhead: "Strategy, design and development for founders who would rather be remembered than noticed.",
            cta: "See the work",
        },
        heroImage: { src: img("photo-1552664730-d307ca884978"), alt: "A team collaborating around a table" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we do",
                body: "Three things, done properly, from first idea to shipped product.",
                cards: [
                    { title: "Strategy", body: "The positioning and story before a single pixel." },
                    { title: "Design", body: "Brand and product design that carries the idea." },
                    { title: "Build", body: "Fast, durable sites and apps that ship on time." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Start a project",
                body: "Tell us what you're building — leave your email to begin.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "consultant",
        name: "Consultant",
        description: "A trustworthy consulting site — a clear hero, services and a booking prompt.",
        category: "business",
        tags: ["business", "consulting", "light", "professional"],
        tier: "premium",
        license: "MIT",
        sourceUrl: source("consultant"),
        layout: "split",
        palette: light("#1d4ed8"),
        nav: ["Services", "About", "Case studies", "Contact"],
        hero: {
            headline: "Solutions that drive growth.",
            subhead: "Business consulting for modern companies — clear advice, measured against results.",
            cta: "Book a call",
        },
        heroImage: { src: img("photo-1507003211169-0a1dd7228f2d"), alt: "A professional in a suit" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How we help",
                body: "Focused engagements that move a real number, not a slide deck.",
                cards: [
                    { title: "Strategy", body: "Where to play and how to win, made concrete." },
                    { title: "Operations", body: "Take the friction out of how the work gets done." },
                    { title: "Growth", body: "Repeatable ways to reach and keep customers." },
                ],
            },
            {
                key: "call",
                label: "Call",
                kind: "form",
                heading: "Book a call",
                body: "Leave your email and we'll find a time that works.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "event",
        name: "Event",
        description: "A one-page event site — a lively hero, the line-up and a registration prompt.",
        category: "event",
        tags: ["event", "conference", "dark", "vibrant"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("event"),
        layout: "full-bleed",
        palette: dark("#a855f7"),
        nav: ["Line-up", "Venue", "Tickets"],
        hero: {
            headline: "An event that stays with you.",
            subhead: "One day, one room, and a line-up worth clearing your calendar for. Plan, celebrate, remember.",
            cta: "Get tickets",
        },
        heroImage: { src: img("photo-1470229722913-7c0e2dbbafd3"), alt: "A crowd at a concert with stage lights" },
        sections: [
            {
                key: "lineup",
                label: "Line-up",
                kind: "cards",
                heading: "The line-up",
                body: "The people worth listening to — full schedule on the day.",
                cards: [
                    { title: "Keynotes", body: "The talks that set the tone for the day." },
                    { title: "Sessions", body: "Hands-on, practical, and short enough to hold attention." },
                    { title: "After hours", body: "The part where the real conversations happen." },
                ],
            },
            {
                key: "register",
                label: "Register",
                kind: "form",
                heading: "Register now",
                body: "Save your seat — leave your email and we'll send your ticket.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    // ------------------------------------------------------------------------------------
    // Designs 13-24 — the second library batch.
    //
    // Each tile's wordmark, navigation, headline, subheading, button label and category are
    // taken exactly from the batch mockup. Everything the mockup does not show — the page
    // body below the hero, the catalogue description, the tier — follows the conventions the
    // first twelve already set: a cards section, a contact form, and `free` until someone
    // prices it (the same default the sourcing normaliser applies).
    // ------------------------------------------------------------------------------------
    buildTemplate({
        id: "cafe",
        name: "Café",
        description: "A cosy café page — a warm hero, what is on the counter and where to find you.",
        category: "food",
        tags: ["food", "cafe", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("cafe"),
        layout: "full-bleed",
        palette: dark("#d4a574"),
        nav: ["Home", "Menu", "About", "Contact"],
        hero: {
            headline: "Good coffee. Good mood.",
            subhead: "A cozy place to relax, work, and enjoy.",
            cta: "View menu",
        },
        heroImage: { src: img("photo-1554118811-1e0d58224f24"), alt: "A coffee cup on a table in a warm café" },
        sections: [
            {
                key: "menu",
                label: "Menu",
                kind: "cards",
                heading: "What we pour",
                body: "Beans roasted close by, pastries baked each morning, and a table you can sit at.",
                cards: [
                    { title: "Coffee", body: "Espresso, filter and everything between, poured properly." },
                    { title: "Pastries", body: "Baked before opening and gone by the afternoon." },
                    { title: "Brunch", body: "Simple plates, served until the kitchen closes." },
                ],
            },
            {
                key: "visit",
                label: "Visit",
                kind: "form",
                heading: "Come and see us",
                body: "Leave your email for opening hours and what is on this week.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "salon",
        name: "Salon",
        description: "A polished salon site — a confident hero, the treatment list and a booking prompt.",
        category: "beauty",
        tags: ["beauty", "salon", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("salon"),
        layout: "full-bleed",
        palette: dark("#e8a0b4"),
        nav: ["Home", "Services", "About", "Gallery", "Contact"],
        hero: {
            headline: "Beauty. Style. Confidence.",
            subhead: "Professional care for a more beautiful you.",
            cta: "Book appointment",
        },
        heroImage: { src: img("photo-1560066984-138dadb4c035"), alt: "A hair salon with styling chairs and mirrors" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we do",
                body: "Cut, colour and care, by people who have done it a long time.",
                cards: [
                    { title: "Cut and style", body: "A shape that suits your hair and the time you have for it." },
                    { title: "Colour", body: "Gloss, balayage or a full change, matched to your tone." },
                    { title: "Treatments", body: "Conditioning and scalp care that makes the rest last." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book your visit",
                body: "Leave your email and we will confirm a time that works.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "real-estate",
        name: "Real Estate",
        description: "A property site — a striking hero, featured listings and a viewing prompt.",
        category: "real_estate",
        tags: ["real_estate", "property", "dark", "modern"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("real-estate"),
        layout: "full-bleed",
        palette: dark("#ffffff"),
        nav: ["Home", "Listings", "About", "Services", "Contact"],
        hero: {
            headline: "Find your dream home today.",
            subhead: "Modern spaces, perfect locations.",
            cta: "View properties",
        },
        heroImage: { src: img("photo-1512917774080-9991f1c4c750"), alt: "A modern house lit up at dusk" },
        sections: [
            {
                key: "listings",
                label: "Listings",
                kind: "cards",
                heading: "On the market",
                body: "A short list, kept current. Ask about anything you do not see here.",
                cards: [
                    { title: "Apartments", body: "City homes close to the places you actually go." },
                    { title: "Family homes", body: "Room to grow into, in neighbourhoods worth staying in." },
                    { title: "New builds", body: "Ready to move into, with everything still under warranty." },
                ],
            },
            {
                key: "viewing",
                label: "Viewing",
                kind: "form",
                heading: "Arrange a viewing",
                body: "Leave your email and we will set up a time to walk through.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "dental-clinic",
        name: "Dental Clinic",
        description: "A reassuring clinic site — a calm hero, the treatments offered and a booking prompt.",
        category: "healthcare",
        tags: ["healthcare", "dental", "dark", "calm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("dental-clinic"),
        layout: "full-bleed",
        palette: dark("#3b82f6"),
        nav: ["Home", "Services", "About", "Doctors", "Contact"],
        hero: {
            headline: "Healthy smile, healthy life.",
            subhead: "Gentle care for you and your family.",
            cta: "Book appointment",
        },
        heroImage: { src: img("photo-1629909613654-28e377c37b09"), alt: "A clean, modern dental treatment room" },
        sections: [
            {
                key: "treatments",
                label: "Treatments",
                kind: "cards",
                heading: "How we can help",
                body: "Routine care and the bigger work, explained before anything begins.",
                cards: [
                    { title: "Check-ups", body: "Twice a year, and the small fixes caught while they are small." },
                    { title: "Hygiene", body: "A proper clean, and how to keep it that way at home." },
                    { title: "Cosmetic", body: "Whitening and straightening, with what to expect said plainly." },
                ],
            },
            {
                key: "appointment",
                label: "Appointment",
                kind: "form",
                heading: "Book an appointment",
                body: "Leave your email and the practice will be in touch with times.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "fitness-coach",
        name: "Fitness Coach",
        description: "A personal-training page — a strong hero, the programmes and a sign-up prompt.",
        category: "fitness",
        tags: ["fitness", "coaching", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("fitness-coach"),
        layout: "full-bleed",
        palette: dark("#22c55e"),
        nav: ["Home", "About", "Programs", "Pricing", "Contact"],
        hero: {
            headline: "Stronger you, better you.",
            subhead: "Personal training tailored to your goals.",
            cta: "Start today",
        },
        heroImage: { src: img("photo-1571019613454-1cb2f99b2d8b"), alt: "A coach training a client in a gym" },
        sections: [
            {
                key: "programs",
                label: "Programs",
                kind: "cards",
                heading: "How we train",
                body: "One-to-one or small group, built around what you can actually commit to.",
                cards: [
                    { title: "One to one", body: "Every session planned around you and how the last one went." },
                    { title: "Small group", body: "Three or four people, so the coaching still reaches you." },
                    { title: "Online", body: "A programme to follow, checked and adjusted every week." },
                ],
            },
            {
                key: "start",
                label: "Start",
                kind: "form",
                heading: "Start this week",
                body: "Leave your email and we will book your first session.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "wedding",
        name: "Wedding",
        description: "A wedding site — a romantic hero, the packages and an enquiry prompt.",
        category: "event",
        tags: ["event", "wedding", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("wedding"),
        layout: "full-bleed",
        palette: dark("#f4b8c1"),
        nav: ["Home", "Our Story", "Gallery", "Services", "Contact"],
        hero: {
            headline: "Celebrate love. Celebrate life.",
            subhead: "Beautiful moments, cherished forever.",
            cta: "View packages",
        },
        heroImage: { src: img("photo-1519741497674-611481863552"), alt: "A floral arch set up for a wedding ceremony" },
        sections: [
            {
                key: "packages",
                label: "Packages",
                kind: "cards",
                heading: "What we arrange",
                body: "As much or as little as you want handled — the day is still yours.",
                cards: [
                    { title: "Ceremony", body: "The setting, the flowers and the order of the day." },
                    { title: "Reception", body: "Room, food and music, run so nobody has to think about it." },
                    { title: "Full planning", body: "From the first idea to the last guest leaving." },
                ],
            },
            {
                key: "enquire",
                label: "Enquire",
                kind: "form",
                heading: "Tell us about your day",
                body: "Leave your email and we will send the packages and dates.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "interior-design",
        name: "Interior Design",
        description: "An interiors studio site — a warm hero, recent projects and a consultation prompt.",
        category: "design",
        tags: ["design", "interiors", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("interior-design"),
        layout: "full-bleed",
        palette: dark("#d9c3a5"),
        nav: ["Home", "Projects", "Services", "About", "Contact"],
        hero: {
            headline: "Designing spaces you'll love.",
            subhead: "Functional. Beautiful. Unforgettable.",
            cta: "View projects",
        },
        heroImage: { src: img("photo-1586023492125-27b2c045efd7"), alt: "A softly lit living room with a sofa and table" },
        sections: [
            {
                key: "projects",
                label: "Projects",
                kind: "cards",
                heading: "Recent work",
                body: "Rooms people live in, not rooms that only photograph well.",
                cards: [
                    { title: "Homes", body: "Whole-house schemes, done room by room or all at once." },
                    { title: "Single rooms", body: "The one space that has never quite worked." },
                    { title: "Workplaces", body: "Offices and studios that people are glad to be in." },
                ],
            },
            {
                key: "consult",
                label: "Consultation",
                kind: "form",
                heading: "Book a consultation",
                body: "Leave your email and we will arrange a first conversation.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "law-firm",
        name: "Law Firm",
        description: "A law-firm site — an authoritative hero, practice areas and a consultation prompt.",
        category: "professional_services",
        tags: ["professional_services", "legal", "dark", "formal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("law-firm"),
        layout: "full-bleed",
        palette: dark("#d6bd8b"),
        nav: ["Home", "Practice Areas", "About", "Attorneys", "Contact"],
        hero: {
            headline: "Your case. Our priority.",
            subhead: "Trusted legal solutions for your peace of mind.",
            cta: "Schedule a consultation",
        },
        heroImage: { src: img("photo-1589829545856-d10d557cf95f"), alt: "Scales of justice beside law books" },
        sections: [
            {
                key: "practice",
                label: "Practice areas",
                kind: "cards",
                heading: "Where we can act",
                body: "The work we do most, and the people who do it.",
                cards: [
                    { title: "Family", body: "Difficult matters handled carefully and without drama." },
                    { title: "Property", body: "Buying, selling and the disputes that come after." },
                    { title: "Commercial", body: "Contracts, disagreements, and keeping you out of court." },
                ],
            },
            {
                key: "consultation",
                label: "Consultation",
                kind: "form",
                heading: "Schedule a consultation",
                body: "Leave your email and we will arrange a first, confidential conversation.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "startup",
        name: "Startup",
        description: "A startup landing page — a confident hero, what you build and a contact prompt.",
        category: "business",
        tags: ["business", "startup", "dark", "modern"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("startup"),
        layout: "full-bleed",
        palette: dark("#2563eb"),
        nav: ["Home", "About", "Services", "Blog", "Contact"],
        hero: {
            headline: "Innovate. Build. Grow.",
            subhead: "We turn ideas into impactful products.",
            cta: "Learn more",
        },
        heroImage: { src: img("photo-1497366216548-37526070297c"), alt: "A bright open-plan office with people working" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we do",
                body: "Small team, short cycles, and something working in front of users early.",
                cards: [
                    { title: "Product", body: "From the first sketch to the thing people actually use." },
                    { title: "Engineering", body: "Built to be changed, because the first version never lasts." },
                    { title: "Growth", body: "Measured, not guessed, and stopped when it stops working." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Get in touch",
                body: "Leave your email and tell us what you are building.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "music-artist",
        name: "Music Artist",
        description: "An artist site — a stage-lit hero, the releases and tour dates.",
        category: "entertainment",
        tags: ["entertainment", "music", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("music-artist"),
        layout: "full-bleed",
        palette: dark("#7c3aed"),
        nav: ["Home", "About", "Music", "Tour", "Contact"],
        hero: {
            headline: "Music that moves you.",
            subhead: "Listen. Feel. Be inspired.",
            cta: "Listen now",
        },
        heroImage: { src: img("photo-1493225457124-a3eb161ffa5f"), alt: "A singer performing under stage lights" },
        sections: [
            {
                key: "music",
                label: "Music",
                kind: "cards",
                heading: "Out now",
                body: "Everything released so far, and where to hear it.",
                cards: [
                    { title: "Latest single", body: "The newest one, and the story behind writing it." },
                    { title: "Albums", body: "The full records, in the order they were meant to be heard." },
                    { title: "Live sessions", body: "Recorded in one take, in rooms with good walls." },
                ],
            },
            {
                key: "tour",
                label: "Tour",
                kind: "form",
                heading: "Tour dates",
                body: "Leave your email and we will tell you when tickets go on sale near you.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "fashion-brand",
        name: "Fashion Brand",
        description: "A fashion storefront — an editorial hero, the collection and an order prompt.",
        category: "store",
        tags: ["store", "fashion", "dark", "minimal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("fashion-brand"),
        layout: "full-bleed",
        palette: dark("#ffffff"),
        nav: ["Home", "Shop", "About", "Lookbook", "Contact"],
        hero: {
            headline: "Timeless style. Made for you.",
            subhead: "Quality pieces. Purposeful design.",
            cta: "Shop collection",
        },
        heroImage: { src: img("photo-1490481651871-ab68de25d43d"), alt: "A model wearing a tailored coat" },
        sections: [
            {
                key: "collection",
                label: "Collection",
                kind: "cards",
                heading: "This season",
                body: "A small range, made well, in fabrics that survive being worn.",
                cards: [
                    { title: "Outerwear", body: "The coat you reach for from October onwards." },
                    { title: "Everyday", body: "Shirts and knitwear cut to be worn, not photographed." },
                    { title: "Accessories", body: "The small things that finish the rest of it." },
                ],
            },
            {
                key: "order",
                label: "Order",
                kind: "form",
                heading: "Stay in the loop",
                body: "Leave your email for new pieces, restocks and sizing help.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "bakery",
        name: "Bakery",
        description: "A bakery page — an inviting hero, what is baked today and an ordering prompt.",
        category: "food",
        tags: ["food", "bakery", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("bakery"),
        layout: "full-bleed",
        palette: dark("#e0a86a"),
        nav: ["Home", "Menu", "About", "Order", "Contact"],
        hero: {
            headline: "Freshly baked happiness.",
            subhead: "Made with love, served with joy.",
            cta: "Order now",
        },
        heroImage: { src: img("photo-1509440159596-0249088772ff"), alt: "Fresh loaves of bread on a bakery shelf" },
        sections: [
            {
                key: "baked",
                label: "Baked today",
                kind: "cards",
                heading: "Out of the oven",
                body: "Baked through the night and set out at opening. When it is gone, it is gone.",
                cards: [
                    { title: "Bread", body: "Slow-proved loaves with a crust worth the wait." },
                    { title: "Pastries", body: "Laminated by hand, best within an hour of opening." },
                    { title: "Cakes", body: "Whole or by the slice, and to order for the weekend." },
                ],
            },
            {
                key: "order",
                label: "Order",
                kind: "form",
                heading: "Order ahead",
                body: "Leave your email to reserve a loaf or ask about a cake.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    // ------------------------------------------------------------------------------------
    // Designs 25-36 — the third library batch. Same rule as the batch above: wordmark, nav,
    // headline, subheading, button label and category come straight from the mockup; the
    // page body, description and tier follow the conventions the earlier designs set.
    // ------------------------------------------------------------------------------------
    buildTemplate({
        id: "hotel",
        name: "Hotel",
        description: "A hotel site — an inviting hero, the rooms on offer and a booking prompt.",
        category: "hospitality",
        tags: ["hospitality", "hotel", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("hotel"),
        layout: "full-bleed",
        palette: dark("#ffffff"),
        nav: ["Home", "Rooms", "Dining", "Offers", "Contact"],
        hero: {
            headline: "Relax. Unwind. Feel at home.",
            subhead: "Luxury stays and unforgettable experiences.",
            cta: "Book your stay",
        },
        heroImage: { src: img("photo-1566073771259-6a8506099945"), alt: "A hotel pool and terrace at dusk" },
        sections: [
            {
                key: "rooms",
                label: "Rooms",
                kind: "cards",
                heading: "Where you will stay",
                body: "Every room made up the same way, whichever one you end up in.",
                cards: [
                    { title: "Double rooms", body: "Quiet, comfortable and bigger than the photographs suggest." },
                    { title: "Suites", body: "A separate sitting room, for when a room is not enough." },
                    { title: "Long stays", body: "Weekly rates for guests who are here to work." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book your stay",
                body: "Leave your email and we will hold a room and send the details.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "travel-agency",
        name: "Travel Agency",
        description: "A travel agency site — a far-away hero, the packages and an enquiry prompt.",
        category: "travel",
        tags: ["travel", "agency", "dark", "vivid"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("travel-agency"),
        layout: "full-bleed",
        palette: dark("#14b8a6"),
        nav: ["Home", "Destinations", "Packages", "About", "Contact"],
        hero: {
            headline: "Discover places. Create memories.",
            subhead: "Custom travel experiences just for you.",
            cta: "Explore packages",
        },
        heroImage: { src: img("photo-1571003123894-1f0594d2b5d9"), alt: "Overwater villas on a turquoise lagoon" },
        sections: [
            {
                key: "packages",
                label: "Packages",
                kind: "cards",
                heading: "Where we can send you",
                body: "Trips planned around what you actually want to do when you get there.",
                cards: [
                    { title: "Escapes", body: "A long weekend somewhere warm, sorted end to end." },
                    { title: "Family trips", body: "Planned so the travelling part is not the hard part." },
                    { title: "Long haul", body: "Multi-stop routes, with the connections that work." },
                ],
            },
            {
                key: "enquire",
                label: "Enquire",
                kind: "form",
                heading: "Plan your trip",
                body: "Leave your email and tell us roughly where and when.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "medical-clinic",
        name: "Medical Clinic",
        description: "A clinic site — a reassuring hero, the services offered and a booking prompt.",
        category: "healthcare",
        tags: ["healthcare", "clinic", "dark", "calm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("medical-clinic"),
        layout: "full-bleed",
        palette: dark("#2563eb"),
        nav: ["Home", "Services", "About", "Doctors", "Contact"],
        hero: {
            headline: "Your health is our priority.",
            subhead: "Compassionate care for you and your family.",
            cta: "Book appointment",
        },
        heroImage: { src: img("photo-1612349317150-e413f6a5b16d"), alt: "A doctor standing in a bright clinic" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How we can help",
                body: "General practice and the specialists we can refer you to.",
                cards: [
                    { title: "Appointments", body: "Same-week where we can, and never rushed once you are in." },
                    { title: "Screening", body: "The routine checks worth keeping up with." },
                    { title: "Follow-up", body: "Someone who has read your notes before you sit down." },
                ],
            },
            {
                key: "appointment",
                label: "Appointment",
                kind: "form",
                heading: "Book an appointment",
                body: "Leave your email and reception will come back with times.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "car-dealership",
        name: "Car Dealership",
        description: "A dealership site — a showroom hero, the stock on offer and a viewing prompt.",
        category: "automotive",
        tags: ["automotive", "cars", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("car-dealership"),
        layout: "full-bleed",
        palette: dark("#dc2626"),
        nav: ["Home", "Inventory", "Services", "About", "Contact"],
        hero: {
            headline: "Drive the best. Be your best.",
            subhead: "Explore our premium collection of cars.",
            cta: "View inventory",
        },
        heroImage: { src: img("photo-1552519507-da3b142c6e3d"), alt: "A car parked in a showroom" },
        sections: [
            {
                key: "inventory",
                label: "Inventory",
                kind: "cards",
                heading: "On the forecourt",
                body: "Everything checked before it goes out, with the history to show for it.",
                cards: [
                    { title: "New", body: "Current models, available to order in the specification you want." },
                    { title: "Approved used", body: "Inspected, warranted, and honest about the mileage." },
                    { title: "Part exchange", body: "Bring what you have and we will value it while you wait." },
                ],
            },
            {
                key: "viewing",
                label: "Viewing",
                kind: "form",
                heading: "Book a test drive",
                body: "Leave your email and tell us which car you would like to drive.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "photography-studio",
        name: "Photography Studio",
        description: "A studio site — a considered hero, the work and a booking prompt.",
        category: "photography",
        tags: ["photography", "studio", "dark", "minimal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("photography-studio"),
        layout: "full-bleed",
        palette: dark("#d6c7b0"),
        nav: ["Home", "Portfolio", "Services", "About", "Contact"],
        hero: {
            headline: "We frame memories beautifully.",
            subhead: "Professional photography for every moment.",
            cta: "View portfolio",
        },
        heroImage: { src: img("photo-1516035069371-29a1b244cc32"), alt: "A photography studio with lighting equipment" },
        sections: [
            {
                key: "work",
                label: "Work",
                kind: "cards",
                heading: "What we shoot",
                body: "Studio and on location, with the same care either way.",
                cards: [
                    { title: "Portraits", body: "One person or a whole family, in an hour, without the ordeal." },
                    { title: "Events", body: "The day as it happened, not as it was posed." },
                    { title: "Commercial", body: "Product and brand work, shot to the brief and on time." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a session",
                body: "Leave your email and tell us what you would like photographed.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "construction",
        name: "Construction",
        description: "A construction firm site — a site hero, recent projects and a quote prompt.",
        category: "business",
        tags: ["business", "construction", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("construction"),
        layout: "full-bleed",
        palette: dark("#f97316"),
        nav: ["Home", "Services", "Projects", "About", "Contact"],
        hero: {
            headline: "Building today. Better tomorrow.",
            subhead: "Reliable construction solutions for all.",
            cta: "Our projects",
        },
        heroImage: { src: img("photo-1541888946425-d81bb19240f5"), alt: "A building under construction against a sunset" },
        sections: [
            {
                key: "projects",
                label: "Projects",
                kind: "cards",
                heading: "What we build",
                body: "Finished on the date we gave you, at the price we quoted.",
                cards: [
                    { title: "Residential", body: "New homes and the extensions that make old ones work." },
                    { title: "Commercial", body: "Units and fit-outs, handed over ready to trade." },
                    { title: "Groundworks", body: "The part nobody sees and everything else depends on." },
                ],
            },
            {
                key: "quote",
                label: "Quote",
                kind: "form",
                heading: "Ask for a quote",
                body: "Leave your email and a short description of the work.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "ngo-nonprofit",
        name: "NGO / Nonprofit",
        description: "A nonprofit site — a human hero, the causes supported and a donation prompt.",
        category: "nonprofit",
        tags: ["nonprofit", "charity", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("ngo-nonprofit"),
        layout: "full-bleed",
        palette: dark("#16a34a"),
        nav: ["Home", "Causes", "About", "Get Involved", "Contact"],
        hero: {
            headline: "Together we can change lives.",
            subhead: "Small actions today, big impact tomorrow.",
            cta: "Donate now",
        },
        heroImage: { src: img("photo-1524995997946-a1c2e315a42f"), alt: "Children smiling together outdoors" },
        sections: [
            {
                key: "causes",
                label: "Causes",
                kind: "cards",
                heading: "Where the money goes",
                body: "Three programmes, and what a donation actually pays for in each.",
                cards: [
                    { title: "Education", body: "Books, fees and the transport that gets a child to school." },
                    { title: "Health", body: "Clinics, check-ups and medicine where there is none." },
                    { title: "Food", body: "Meals now, and the training that makes them unnecessary later." },
                ],
            },
            {
                key: "involved",
                label: "Get involved",
                kind: "form",
                heading: "Get involved",
                body: "Leave your email to hear about volunteering and where help is needed.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "university",
        name: "University",
        description: "A university site — a campus hero, the programmes and an admissions prompt.",
        category: "education",
        tags: ["education", "university", "dark", "formal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("university"),
        layout: "full-bleed",
        palette: dark("#3b82f6"),
        nav: ["Home", "Academics", "Admissions", "Campus", "Contact"],
        hero: {
            headline: "Shape your future with us.",
            subhead: "World-class education for a better tomorrow.",
            cta: "Explore programs",
        },
        heroImage: { src: img("photo-1504307651254-35680f356dfd"), alt: "A university building on a green campus" },
        sections: [
            {
                key: "academics",
                label: "Academics",
                kind: "cards",
                heading: "What you can study",
                body: "Taught by people doing the work, not only reading about it.",
                cards: [
                    { title: "Undergraduate", body: "Three and four year degrees across every faculty." },
                    { title: "Postgraduate", body: "Taught masters and research, full or part time." },
                    { title: "Short courses", body: "A term at a time, for people already working." },
                ],
            },
            {
                key: "admissions",
                label: "Admissions",
                kind: "form",
                heading: "Apply to study",
                body: "Leave your email for prospectuses, open days and deadlines.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "online-course",
        name: "Online Course",
        description: "An online course site — a study hero, the curriculum and an enrolment prompt.",
        category: "education",
        tags: ["education", "online", "dark", "modern"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("online-course"),
        layout: "full-bleed",
        palette: dark("#8b5cf6"),
        nav: ["Home", "Courses", "Instructors", "Pricing", "Contact"],
        hero: {
            headline: "Learn anytime. Achieve more.",
            subhead: "Expert-led courses to boost your skills.",
            cta: "Browse courses",
        },
        heroImage: { src: img("photo-1531297484001-80022131f5a1"), alt: "A laptop open on a desk showing a lesson" },
        sections: [
            {
                key: "courses",
                label: "Courses",
                kind: "cards",
                heading: "What you will learn",
                body: "Short lessons you can finish, rather than a library you never open.",
                cards: [
                    { title: "Foundations", body: "The first week, assuming you know nothing yet." },
                    { title: "Practice", body: "Exercises marked by a person, not a multiple choice box." },
                    { title: "Projects", body: "Something finished and yours by the end of it." },
                ],
            },
            {
                key: "enrol",
                label: "Enrol",
                kind: "form",
                heading: "Start learning",
                body: "Leave your email and we will send the first lesson free.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "freelancer",
        name: "Freelancer",
        description: "A freelancer site — a workspace hero, the services offered and a hire prompt.",
        category: "portfolio",
        tags: ["portfolio", "freelance", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("freelancer"),
        layout: "full-bleed",
        palette: dark("#14b8a6"),
        nav: ["Home", "Services", "Work", "About", "Contact"],
        hero: {
            headline: "Freelance services that deliver.",
            subhead: "Helping brands build with creativity.",
            cta: "Hire me",
        },
        heroImage: { src: img("photo-1523240795612-9a054b0db644"), alt: "A desk with a laptop and a warm lamp" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How I can help",
                body: "A small number of things, done properly, one client at a time.",
                cards: [
                    { title: "Design", body: "Brand and interface work, from the first sketch onwards." },
                    { title: "Build", body: "Sites that load fast and survive being edited later." },
                    { title: "Consulting", body: "A day of questions, and a plan you can act on." },
                ],
            },
            {
                key: "hire",
                label: "Hire",
                kind: "form",
                heading: "Start a project",
                body: "Leave your email and a line about what you need.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "tech-company",
        name: "Tech Company",
        description: "A technology company site — a confident hero, the solutions and a contact prompt.",
        category: "business",
        tags: ["business", "technology", "dark", "modern"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("tech-company"),
        layout: "full-bleed",
        palette: dark("#2563eb"),
        nav: ["Home", "About", "Solutions", "Careers", "Contact"],
        hero: {
            headline: "Technology that moves the world forward.",
            subhead: "Innovative solutions for a digital future.",
            cta: "Our solutions",
        },
        heroImage: { src: img("photo-1522202176988-66273c2fd55f"), alt: "A team working together at screens" },
        sections: [
            {
                key: "solutions",
                label: "Solutions",
                kind: "cards",
                heading: "What we do",
                body: "Systems that hold up when the people who built them have moved on.",
                cards: [
                    { title: "Platform", body: "The parts every product needs, built once and shared." },
                    { title: "Data", body: "Numbers you can act on, and a way to check them." },
                    { title: "Support", body: "People who answer, and fixes that stay fixed." },
                ],
            },
            {
                key: "contact",
                label: "Contact",
                kind: "form",
                heading: "Talk to us",
                body: "Leave your email and we will arrange a call.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "podcast",
        name: "Podcast",
        description: "A podcast site — a studio hero, the episodes and a subscribe prompt.",
        category: "media",
        tags: ["media", "podcast", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("podcast"),
        layout: "full-bleed",
        palette: dark("#7c3aed"),
        nav: ["Home", "Episodes", "About", "Contact"],
        hero: {
            headline: "Real conversations. Real impact.",
            subhead: "Stories, insights and ideas that matter.",
            cta: "Listen now",
        },
        heroImage: { src: img("photo-1478737270239-2f02b77fc618"), alt: "A studio microphone under an on-air sign" },
        sections: [
            {
                key: "episodes",
                label: "Episodes",
                kind: "cards",
                heading: "Recent episodes",
                body: "An hour a fortnight, edited down from rather more than that.",
                cards: [
                    { title: "Interviews", body: "One guest, one subject, and time to get past the surface." },
                    { title: "Deep dives", body: "The whole story of one thing, researched properly." },
                    { title: "Listener mail", body: "Your questions, answered on air and at length." },
                ],
            },
            {
                key: "subscribe",
                label: "Subscribe",
                kind: "form",
                heading: "Never miss an episode",
                body: "Leave your email and we will tell you when a new one is out.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    // ------------------------------------------------------------------------------------
    // Designs 37-51 — the fourth library batch, on the same rule as the batches above.
    //
    // Several sit next to an earlier design in the same bucket on purpose: Auto Service
    // beside Car Dealership, Online Learning beside Online Course, Interior Design Studio
    // beside Interior Design, Real Estate Agent beside Real Estate. They are the mockup's
    // designs and they stay distinct entries.
    // ------------------------------------------------------------------------------------
    buildTemplate({
        id: "sports-club",
        name: "Sports Club",
        description: "A sports club site — an action hero, the teams and a membership prompt.",
        category: "sports",
        tags: ["sports", "club", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("sports-club"),
        layout: "full-bleed",
        palette: dark("#22c55e"),
        nav: ["Home", "About", "Teams", "Events", "Contact"],
        hero: {
            headline: "Play together. Win together.",
            subhead: "Building champions on and off the field.",
            cta: "Join the club",
        },
        heroImage: { src: img("photo-1517649763962-0c623066013b"), alt: "A footballer playing under floodlights" },
        sections: [
            {
                key: "teams",
                label: "Teams",
                kind: "cards",
                heading: "Who plays here",
                body: "Sides at every age and level, training through the week.",
                cards: [
                    { title: "Juniors", body: "From first touch to first match, coached properly." },
                    { title: "Seniors", body: "League football on Saturdays, training on Tuesdays." },
                    { title: "Veterans", body: "Slower, wiser, and still competitive on a good day." },
                ],
            },
            {
                key: "join",
                label: "Join",
                kind: "form",
                heading: "Join the club",
                body: "Leave your email and we will tell you when trials are on.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "yoga-studio",
        name: "Yoga Studio",
        description: "A yoga studio site — a calm hero, the class timetable and a booking prompt.",
        category: "health_wellness",
        tags: ["health_wellness", "yoga", "dark", "calm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("yoga-studio"),
        layout: "full-bleed",
        palette: dark("#f0abfc"),
        nav: ["Home", "Classes", "About", "Gallery", "Contact"],
        hero: {
            headline: "Breathe. Stretch. Find balance.",
            subhead: "Yoga for a healthier body and mind.",
            cta: "View classes",
        },
        heroImage: { src: img("photo-1506126613408-eca07ce68773"), alt: "A person practising yoga in a bright room" },
        sections: [
            {
                key: "classes",
                label: "Classes",
                kind: "cards",
                heading: "On the timetable",
                body: "Small classes, so the teacher can actually see you.",
                cards: [
                    { title: "Beginners", body: "The first eight weeks, assuming you have never tried." },
                    { title: "Vinyasa", body: "Moving with the breath, at a pace that builds." },
                    { title: "Restorative", body: "Slow, supported, and longer holds. Bring socks." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a class",
                body: "Leave your email and we will send the timetable and a first class free.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "spa-wellness",
        name: "Spa & Wellness",
        description: "A spa site — a restful hero, the treatment list and a booking prompt.",
        category: "health_wellness",
        tags: ["health_wellness", "spa", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("spa-wellness"),
        layout: "full-bleed",
        palette: dark("#d4b483"),
        nav: ["Home", "Services", "About", "Contact"],
        hero: {
            headline: "Relax. Refresh. Rejuvenate.",
            subhead: "Premium spa and wellness experiences for you.",
            cta: "Book now",
        },
        heroImage: { src: img("photo-1540555700478-4be289fbecef"), alt: "Rolled towels and candles in a spa" },
        sections: [
            {
                key: "treatments",
                label: "Treatments",
                kind: "cards",
                heading: "What we offer",
                body: "An hour that is genuinely yours, with the phone left at reception.",
                cards: [
                    { title: "Massage", body: "Deep tissue or gentle, said out loud before we start." },
                    { title: "Facials", body: "Matched to your skin rather than to a menu." },
                    { title: "Day packages", body: "Several treatments and the time between them." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a treatment",
                body: "Leave your email and we will find you a time.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "pet-care",
        name: "Pet Care",
        description: "A pet care site — a friendly hero, the services offered and a booking prompt.",
        category: "pets",
        tags: ["pets", "grooming", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("pet-care"),
        layout: "full-bleed",
        palette: dark("#f97316"),
        nav: ["Home", "Services", "About", "Contact"],
        hero: {
            headline: "Happy pets, Happy life.",
            subhead: "Care, love and attention they deserve.",
            cta: "Our services",
        },
        heroImage: { src: img("photo-1601758174114-e711c0cbaa69"), alt: "A dog being cared for by a groomer" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How we help",
                body: "Looked after by the same people each time, so your pet knows them.",
                cards: [
                    { title: "Grooming", body: "Wash, clip and nails, without the drama." },
                    { title: "Day care", body: "Company and a walk while you are at work." },
                    { title: "Boarding", body: "Overnight stays with their own bed and routine." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book a visit",
                body: "Leave your email and tell us about your pet.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "auto-service",
        name: "Auto Service",
        description: "A garage site — a workshop hero, the services offered and a booking prompt.",
        category: "automotive",
        tags: ["automotive", "garage", "dark", "practical"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("auto-service"),
        layout: "full-bleed",
        palette: dark("#3b82f6"),
        nav: ["Home", "Services", "About", "Contact"],
        hero: {
            headline: "We keep you moving.",
            subhead: "Reliable car care and repair services.",
            cta: "Book service",
        },
        heroImage: { src: img("photo-1487754180451-c456f719a1fc"), alt: "A mechanic working under a car bonnet" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we do",
                body: "A quote before the work, and a call before anything changes.",
                cards: [
                    { title: "Servicing", body: "Manufacturer schedules without the main dealer price." },
                    { title: "MOT and repairs", body: "Tested here, fixed here, back on the road here." },
                    { title: "Diagnostics", body: "The warning light explained in words that mean something." },
                ],
            },
            {
                key: "book",
                label: "Book",
                kind: "form",
                heading: "Book your car in",
                body: "Leave your email with your registration and what it is doing.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "art-gallery",
        name: "Art Gallery",
        description: "A gallery site — a spacious hero, current exhibitions and a visit prompt.",
        category: "arts_culture",
        tags: ["arts_culture", "gallery", "dark", "minimal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("art-gallery"),
        layout: "full-bleed",
        palette: dark("#a78bfa"),
        nav: ["Exhibitions", "Artists", "About", "Contact"],
        hero: {
            headline: "Where art inspires life.",
            subhead: "Discover, appreciate and collect art.",
            cta: "View exhibitions",
        },
        heroImage: { src: img("photo-1595152772835-219674b2a8a6"), alt: "Paintings hung along a gallery wall" },
        sections: [
            {
                key: "exhibitions",
                label: "Exhibitions",
                kind: "cards",
                heading: "On now",
                body: "Three rooms, changed through the year, free to walk into.",
                cards: [
                    { title: "Main gallery", body: "The season's headline show, six weeks at a time." },
                    { title: "Project space", body: "Newer work, often by artists showing for the first time." },
                    { title: "Collection", body: "What the gallery owns, rotated so it is not always the same." },
                ],
            },
            {
                key: "visit",
                label: "Visit",
                kind: "form",
                heading: "Plan a visit",
                body: "Leave your email for opening hours and what is coming next.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "bookstore",
        name: "Bookstore",
        description: "A bookshop site — a shelf-lined hero, what is in stock and an events prompt.",
        category: "retail",
        tags: ["retail", "books", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("bookstore"),
        layout: "full-bleed",
        palette: dark("#22c55e"),
        nav: ["Home", "Books", "Events", "About", "Contact"],
        hero: {
            headline: "Books for every reader.",
            subhead: "Discover your next favorite book.",
            cta: "Shop now",
        },
        heroImage: { src: img("photo-1541963463532-d68292c34b19"), alt: "Books stacked on shelves in a bookshop" },
        sections: [
            {
                key: "shelves",
                label: "Shelves",
                kind: "cards",
                heading: "What is in",
                body: "Chosen by people who have read them, not by an algorithm.",
                cards: [
                    { title: "New releases", body: "This month's, with a note on why each is here." },
                    { title: "Staff picks", body: "The ones we press into people's hands." },
                    { title: "Second hand", body: "Older, cheaper, and often better." },
                ],
            },
            {
                key: "events",
                label: "Events",
                kind: "form",
                heading: "Readings and events",
                body: "Leave your email and we will tell you who is reading next.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "real-estate-agent",
        name: "Real Estate Agent",
        description: "An agent's site — a homely hero, current properties and a viewing prompt.",
        category: "real_estate",
        tags: ["real_estate", "agent", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("real-estate-agent"),
        layout: "full-bleed",
        palette: dark("#d6bd8b"),
        nav: ["Home", "Properties", "About", "Contact"],
        hero: {
            headline: "Find the perfect place to call home.",
            subhead: "Personalized service. Trusted guidance.",
            cta: "Explore properties",
        },
        heroImage: { src: img("photo-1560518883-ce09059eeffa"), alt: "An estate agent in a bright living room" },
        sections: [
            {
                key: "properties",
                label: "Properties",
                kind: "cards",
                heading: "Currently listed",
                body: "One agent from first viewing to handing over the keys.",
                cards: [
                    { title: "For sale", body: "Priced to sell, described as they actually are." },
                    { title: "To let", body: "Managed properties with a landlord who answers." },
                    { title: "Valuations", body: "An honest number, free, with no obligation after." },
                ],
            },
            {
                key: "viewing",
                label: "Viewing",
                kind: "form",
                heading: "Arrange a viewing",
                body: "Leave your email and which property you would like to see.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "recruitment-agency",
        name: "Recruitment Agency",
        description: "A recruitment site — a people-led hero, the services and a hiring prompt.",
        category: "business",
        tags: ["business", "recruitment", "dark", "modern"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("recruitment-agency"),
        layout: "full-bleed",
        palette: dark("#8b5cf6"),
        nav: ["Home", "Services", "About", "Jobs", "Contact"],
        hero: {
            headline: "The right people for the right job.",
            subhead: "Connecting talent with opportunities.",
            cta: "Find talent",
        },
        heroImage: { src: img("photo-1497215728101-856f4ea42174"), alt: "Two people talking across a desk in an office" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "How we work",
                body: "Fewer candidates, each of whom has actually been spoken to.",
                cards: [
                    { title: "Permanent", body: "Hires who are still there in two years." },
                    { title: "Contract", body: "Someone competent, starting this month." },
                    { title: "Executive", body: "Discreet searches, handled by one person throughout." },
                ],
            },
            {
                key: "hiring",
                label: "Hiring",
                kind: "form",
                heading: "Tell us who you need",
                body: "Leave your email and the role you are trying to fill.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "financial-advisor",
        name: "Financial Advisor",
        description: "An adviser's site — a considered hero, the services and a consultation prompt.",
        category: "finance",
        tags: ["finance", "advice", "dark", "formal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("financial-advisor"),
        layout: "full-bleed",
        palette: dark("#2563eb"),
        nav: ["Projects", "Services", "About", "Resources", "Contact"],
        hero: {
            headline: "Plan today. Secure tomorrow.",
            subhead: "Smart financial advice for a better future.",
            cta: "Book a consultation",
        },
        heroImage: { src: img("photo-1554224155-6726b3ff858f"), alt: "Financial charts reviewed on a tablet" },
        sections: [
            {
                key: "services",
                label: "Services",
                kind: "cards",
                heading: "What we advise on",
                body: "Fees explained before any advice, and no product we are paid to sell.",
                cards: [
                    { title: "Retirement", body: "What you will have, and what it will be worth by then." },
                    { title: "Investments", body: "A portfolio you understand and can leave alone." },
                    { title: "Protection", body: "Cover for the things that would actually derail you." },
                ],
            },
            {
                key: "consultation",
                label: "Consultation",
                kind: "form",
                heading: "Book a consultation",
                body: "Leave your email and we will arrange a first meeting, free.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "investment-firm",
        name: "Investment Firm",
        description: "An investment firm site — a confident hero, the strategies and an enquiry prompt.",
        category: "finance",
        tags: ["finance", "investment", "dark", "formal"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("investment-firm"),
        layout: "full-bleed",
        palette: dark("#3b82f6"),
        nav: ["Home", "Services", "About", "Insights", "Contact"],
        hero: {
            headline: "Invest with confidence.",
            subhead: "Strategic investments for long-term growth.",
            cta: "Explore opportunities",
        },
        heroImage: { src: img("photo-1611974789855-9c2a0a7236a3"), alt: "A city skyline at night" },
        sections: [
            {
                key: "strategies",
                label: "Strategies",
                kind: "cards",
                heading: "How we invest",
                body: "Long horizons, published holdings, and the fees on the same page.",
                cards: [
                    { title: "Core", body: "Broad, cheap and boring, which is the point." },
                    { title: "Growth", body: "Concentrated positions held for years, not quarters." },
                    { title: "Income", body: "Built to pay out steadily rather than to look clever." },
                ],
            },
            {
                key: "enquire",
                label: "Enquire",
                kind: "form",
                heading: "Speak to the team",
                body: "Leave your email and we will send the current factsheets.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "tennis-academy",
        name: "Tennis Academy",
        description: "A tennis academy site — a court-side hero, the programmes and a joining prompt.",
        category: "sports",
        tags: ["sports", "tennis", "dark", "bold"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("tennis-academy"),
        layout: "full-bleed",
        palette: dark("#22c55e"),
        nav: ["Home", "Programs", "Coaches", "Contact"],
        hero: {
            headline: "Train. Compete. Achieve.",
            subhead: "Professional coaching for all levels.",
            cta: "Join now",
        },
        heroImage: { src: img("photo-1533929736458-ca588d08c8be"), alt: "A tennis player mid-serve on a court" },
        sections: [
            {
                key: "programs",
                label: "Programs",
                kind: "cards",
                heading: "How we coach",
                body: "Courts booked in blocks, so you play with the same people each week.",
                cards: [
                    { title: "Beginners", body: "Grip, footwork and a rally by the end of the term." },
                    { title: "Squads", body: "Group sessions by standard, moving up when you are ready." },
                    { title: "Performance", body: "Match play, video and a schedule for the season." },
                ],
            },
            {
                key: "join",
                label: "Join",
                kind: "form",
                heading: "Join the academy",
                body: "Leave your email and we will match you to a squad.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "online-learning",
        name: "Online Learning",
        description: "An online learning site — a focused hero, the courses and an enrolment prompt.",
        category: "education",
        tags: ["education", "online", "dark", "calm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("online-learning"),
        layout: "full-bleed",
        palette: dark("#8b5cf6"),
        nav: ["Courses", "Instructors", "About", "Contact"],
        hero: {
            headline: "Learn today. Lead tomorrow.",
            subhead: "Flexible online courses to upskill your future.",
            cta: "Browse courses",
        },
        heroImage: { src: img("photo-1517245386807-bb43f82c33c4"), alt: "A learner at a laptop wearing headphones" },
        sections: [
            {
                key: "courses",
                label: "Courses",
                kind: "cards",
                heading: "What you can take",
                body: "Study around the job you already have, at the pace that fits.",
                cards: [
                    { title: "Short courses", body: "Six weeks, an evening at a time." },
                    { title: "Certificates", body: "Assessed properly, and worth putting on a CV." },
                    { title: "Live cohorts", body: "A start date, a group, and someone expecting you." },
                ],
            },
            {
                key: "enrol",
                label: "Enrol",
                kind: "form",
                heading: "Start learning",
                body: "Leave your email and we will send the prospectus and dates.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "interior-design-studio",
        name: "Interior Design Studio",
        description: "An interiors studio site — a lived-in hero, the projects and a consultation prompt.",
        category: "design",
        tags: ["design", "studio", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("interior-design-studio"),
        layout: "full-bleed",
        palette: dark("#d9c3a5"),
        nav: ["Projects", "Services", "About", "Contact"],
        hero: {
            headline: "Designing spaces that reflect you.",
            subhead: "Beautiful. Functional. Timeless.",
            cta: "View projects",
        },
        heroImage: { src: img("photo-1616486338812-3dadae4b4ace"), alt: "A calm living room with warm furnishings" },
        sections: [
            {
                key: "projects",
                label: "Projects",
                kind: "cards",
                heading: "Recent projects",
                body: "Schemes that still work three years in, once real life has moved in.",
                cards: [
                    { title: "Full house", body: "Every room, planned together so nothing fights." },
                    { title: "Renovation", body: "Old buildings brought up to date without stripping them out." },
                    { title: "Styling", body: "The last ten per cent that makes a room finished." },
                ],
            },
            {
                key: "consult",
                label: "Consultation",
                kind: "form",
                heading: "Start a project",
                body: "Leave your email and a little about the space.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
    buildTemplate({
        id: "catering-service",
        name: "Catering Service",
        description: "A catering site — an abundant hero, the menus and an enquiry prompt.",
        category: "food",
        tags: ["food", "catering", "dark", "warm"],
        tier: "free",
        license: "MIT",
        sourceUrl: source("catering-service"),
        layout: "full-bleed",
        palette: dark("#f97316"),
        nav: ["Services", "Menus", "About", "Contact"],
        hero: {
            headline: "Good food. Great moments.",
            subhead: "Delicious catering for every occasion.",
            cta: "View menu",
        },
        heroImage: { src: img("photo-1530023367847-a683933f4172"), alt: "A catering buffet laid out on a long table" },
        sections: [
            {
                key: "menus",
                label: "Menus",
                kind: "cards",
                heading: "What we cook",
                body: "Cooked on the day, near where it is served, for any number of people.",
                cards: [
                    { title: "Weddings", body: "A tasting first, then exactly that on the day." },
                    { title: "Corporate", body: "Lunches and launches, delivered and set up." },
                    { title: "Private", body: "Dinner at your table, cleared away before we leave." },
                ],
            },
            {
                key: "enquire",
                label: "Enquire",
                kind: "form",
                heading: "Ask about your event",
                body: "Leave your email with the date and how many people.",
            },
        ],
        footer: "Built with PageCraft.",
    }),
];
