import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { loadTemplate, listTemplates } from '@/lib/ai/harness/templates';
import { registryVars } from '@/lib/ai/harness/registry-vars';
import { guidanceFor } from '@/lib/ai/harness/guidance';
import { aiConfig } from '@/lib/ai/config';
import {
    SECTION_KEYS, THEME_IDS, MOTION_IDS, RADIUS_IDS, SPACING_IDS, IMAGERY_IDS, TONE_IDS,
} from '@/lib/contracts';
import { SECTION_CONTRACTS } from '@/lib/ai/sections/contracts';
import { THEMES } from '@/lib/render/art-direction';
import { TONE_THEMES, TONE_MOTIONS } from '@/lib/ai/art-direction/tone-map';

/**
 * D19 — the prompt library reference.
 *
 * Generated from the prompt files rather than written beside them. A
 * hand-written inventory of prompts is out of date the first time someone adds
 * a version, and a stale reference is worse than none: it is the document
 * people trust while it lies. `npm run prompts:doc` regenerates it, and a test
 * asserts the committed copy matches what the generator produces.
 */

const DIR = join(process.cwd(), 'src/lib/ai/harness/prompts');
const GUIDANCE_DIR = join(DIR, 'guidance');

const digest = (text: string) =>
    createHash('sha256').update(text.replace(/\r\n/g, '\n')).digest('hex').slice(0, 12);

const PURPOSE: Record<string, string> = {
    classify: 'free text → category, vertical, tone, palette, sections',
    profile: 'vertical → section recipe, art direction, vocabulary',
    plan: 'recipe + description → ordered sections with layout variants',
    'fill-section': 'one section → typed content fields',
    edit: 'one section + instruction → changed fields',
};

/** Which stage loads which file, from config — the live answer, not a guess. */
function activeVersions(): Record<string, string> {
    const { prompts } = aiConfig();
    return {
        classify: prompts.classify,
        profile: prompts.profile,
        plan: prompts.plan,
        'fill-section': prompts.fill,
        edit: prompts.edit,
    };
}

function placeholdersIn(text: string): string[] {
    return [...new Set([...text.matchAll(/\{\{(\w+)\}\}/g)].map((m) => m[1]))].sort();
}

export function buildPromptLibrary(): string {
    const files = listTemplates().sort();
    const active = activeVersions();
    const registry = new Set(Object.keys(registryVars()));

    const lines: string[] = [
        '# Prompt library',
        '',
        '> Generated by `npm run prompts:doc`. Do not edit by hand — a stale',
        '> inventory is the document people trust while it lies.',
        '',
        'Every prompt the pipeline can load, what it is for, what fills it, and',
        'the digest of the exact bytes on disk. A version number marks a decision:',
        'to change what a prompt asks for, add a version rather than editing one.',
        '',
        '## In use right now',
        '',
        '| Stage | File | Set by |',
        '|---|---|---|',
    ];

    const envFor: Record<string, string> = {
        classify: 'AI_PROMPT_CLASSIFY',
        profile: 'AI_PROMPT_PROFILE',
        plan: 'AI_PROMPT_PLAN',
        'fill-section': 'AI_PROMPT_FILL',
        edit: 'AI_PROMPT_EDIT',
    };

    for (const [id, file] of Object.entries(active)) {
        lines.push(`| ${id} | \`${file}.md\` | \`${envFor[id]}\` |`);
    }

    lines.push(
        '',
        'Switching a stage to another version is a config change, so an A/B is a',
        'run of the same binary rather than a branch:',
        '',
        '```bash',
        'AI_PROMPT_PLAN=plan.v2 AI_PROMPT_FILL=fill-section.v2 npm run grade -- --label=v2',
        '```',
        '',
        '## Every prompt on disk',
        '',
        '| File | Id | Version | Tier | Digest | Purpose |',
        '|---|---|---|---|---|---|',
    );

    for (const file of files) {
        const tpl = loadTemplate(file);
        const raw = readFileSync(join(DIR, file), 'utf8');
        const inUse = active[tpl.id] === file.replace(/\.md$/, '');
        lines.push(
            `| \`${file}\`${inUse ? ' ←' : ''} | ${tpl.id} | ${tpl.version} | ${tpl.tier} `
            + `| \`${digest(raw)}\` | ${PURPOSE[tpl.id] ?? '—'} |`,
        );
    }

    // ── variables ──────────────────────────────────────────────────────────
    lines.push(
        '',
        '## Variables',
        '',
        'Registry lists are merged in automatically by `render()`, so a prompt can',
        'name one without its caller knowing and no list is hand-copied into a',
        'second place. Per-call values are supplied by the stage that loads the',
        'prompt. A placeholder that is neither is a typo, and a test fails on it.',
        '',
        '| Prompt | Registry lists | Per-call values |',
        '|---|---|---|',
    );

    for (const file of files) {
        const tpl = loadTemplate(file);
        const used = placeholdersIn(`${tpl.system}\n${tpl.user}`);
        const fromRegistry = used.filter((v) => registry.has(v));
        const perCall = used.filter((v) => !registry.has(v));
        lines.push(
            `| \`${file}\` | ${fromRegistry.map((v) => `\`${v}\``).join(', ') || '—'} `
            + `| ${perCall.map((v) => `\`${v}\``).join(', ') || '—'} |`,
        );
    }

    lines.push(
        '',
        '### Registry lists, and where they come from',
        '',
        '| Placeholder | Source of truth |',
        '|---|---|',
        '| `categories` | `CATEGORY_IDS` — `contracts/template.ts` |',
        '| `tones`, `palettes` | `TONE_IDS`, `PALETTE_IDS` — `contracts/ai.ts` |',
        '| `sectionKeys` | `SECTION_KEYS` — `contracts/ai.ts` |',
        '| `themes`, `motions`, `radii`, `spacings`, `imagery` | the art-direction registries — `contracts/ai.ts` |',
        '| `variantMenu` | `variantMenu()` — generated from the section contracts |',
    );

    // ── guidance ───────────────────────────────────────────────────────────
    const guidanceFiles = existsSync(GUIDANCE_DIR)
        ? readdirSync(GUIDANCE_DIR).filter((f) => f.endsWith('.md')).sort()
        : [];

    lines.push(
        '',
        '## Per-section-type guidance',
        '',
        'Selected in `generate/fill.ts` and passed as `{{guidance}}`. The harness has',
        'no conditionals, so the block is chosen in code and kept on disk as text —',
        'tuning a section\'s voice stays a text edit. A section type with no file gets',
        'the general rules in the prompt body and nothing more.',
        '',
        '| Section | File | Digest | First line |',
        '|---|---|---|---|',
    );

    for (const key of SECTION_KEYS) {
        const file = `${key}.md`;
        const path = join(GUIDANCE_DIR, file);
        if (!existsSync(path)) {
            lines.push(`| ${key} | — | — | _(none)_ |`);
            continue;
        }
        const raw = readFileSync(path, 'utf8');
        const first = raw.trim().split('\n')[0].slice(0, 80);
        lines.push(`| ${key} | \`guidance/${file}\` | \`${digest(raw)}\` | ${first} |`);
    }

    const orphans = guidanceFiles.filter(
        (f) => !(SECTION_KEYS as readonly string[]).includes(f.replace(/\.md$/, '')),
    );
    if (orphans.length) {
        lines.push('', `Unused guidance files (no such section type): ${orphans.join(', ')}`);
    }

    // ── containment ────────────────────────────────────────────────────────
    lines.push(
        '',
        '## Containment',
        '',
        'No prompt carries the data/instruction boundary itself. Every untrusted',
        'value is wrapped by `containment/envelope.ts` before interpolation, and the',
        'containment paragraph is attached to the system message from one place',
        '(FR-110, M3.7). A rule living in five prompt files is a rule waiting to be',
        'missed in the sixth.',
        '',
        '| Stage | Untrusted | Trusted |',
        '|---|---|---|',
        '| classify | the description | the prompt file |',
        '| plan | the description, the recipe | the prompt file |',
        '| fill-section | the description, the brief | the prompt file |',
        '| edit | the section\'s stored content | the user\'s instruction |',
        '| profile | *nothing* — its only input is a normalised slug | |',
        '',
        '`edit.v1` also carries the containment paragraph inline. That is now belt',
        'and braces rather than the only copy, and a test still asserts its wording.',
        '',
    );

    // ── section content contracts ──────────────────────────────────────────
    lines.push(
        '## Section content contracts',
        '',
        'The fill stage is typed against these, not against free-form HTML. A field',
        'rename here is a schema change; the prompt lists the keys so the model and',
        'the contract cannot drift. Optional facts (phone, email, address, hours) may',
        'be empty — dummy placeholders are scrubbed, not published.',
        '',
        '| Section | Variants | Fields |',
        '|---|---|---|',
    );

    for (const key of SECTION_KEYS) {
        const c = SECTION_CONTRACTS[key];
        const fields = c.fields.map((f) => {
            const opt = f.optional ? '?' : '';
            return `\`${f.key}${opt}\` (${f.type})`;
        }).join(', ');
        lines.push(`| ${c.type} | ${c.variants.join(', ')} | ${fields} |`);
    }

    // ── art-direction dials ────────────────────────────────────────────────
    lines.push(
        '',
        '## Art-direction dial vocabulary',
        '',
        'Five dials, chosen by the profile (constrained by classified tone) and',
        'applied at render as CSS custom properties. D14 wired them; D16 keeps a',
        'rolling sample from collapsing onto one look.',
        '',
        '### Themes (8)',
        '',
        '| Id | Label |',
        '|---|---|',
        ...THEME_IDS.map((id) => `| \`${id}\` | ${THEMES[id].label} |`),
        '',
        '### Motion',
        '',
        MOTION_IDS.map((id) => `\`${id}\``).join(', '),
        '',
        '### Radius / spacing / imagery',
        '',
        `| Radius | ${RADIUS_IDS.map((id) => `\`${id}\``).join(', ')} |`,
        `| Spacing | ${SPACING_IDS.map((id) => `\`${id}\``).join(', ')} |`,
        `| Imagery | ${IMAGERY_IDS.map((id) => `\`${id}\``).join(', ')} |`,
        '',
        '### Tone constraints',
        '',
        'Classified tone does not pin a single theme. It *constrains* the allowed',
        'set; the profile look stays when it already fits (the D11 48% collapse',
        'was `formal` → `clinical-blue` / `whisper`).',
        '',
        '| Tone | Themes | Motions |',
        '|---|---|---|',
        ...TONE_IDS.map((tone) =>
            `| ${tone} | ${TONE_THEMES[tone].join(', ')} | ${TONE_MOTIONS[tone].join(', ')} |`),
        '',
        '## Day-19 freeze',
        '',
        'A process freeze, not a code dump of the product. Frozen:',
        '',
        '- **v1 prompt files** — hash-pinned in `tests/unit/ai-templates.test.ts`.',
        '  Every eval on record was produced by those bytes. Add a version; do not',
        '  edit v1.',
        '- **Section content contract field names** — a rename is a schema change.',
        '- **Art-direction dial ids** — `THEME_IDS`, `MOTION_IDS`, `RADIUS_IDS`,',
        '  `SPACING_IDS`, `IMAGERY_IDS`.',
        '',
        'Not frozen: v3 prompts (switched via `AI_PROMPT_PLAN` / `AI_PROMPT_FILL`),',
        'the catalogue, or the rest of the product.',
        '',
        '## Rules',
        '',
        '- **Allowed-value lists belong in the response schema, not the prose.** A rule',
        '  in a prompt is a request; a schema is a constraint. They appear in prose only',
        '  where the model benefits from seeing the vocabulary while it reasons.',
        '- **v1 is frozen.** Its five files are hash-pinned in CI. Every eval result on',
        '  record was produced by those exact bytes, so editing one invalidates the',
        '  table it appears in.',
        '- **Name the filler you do not want.** "Never write \'Welcome to our website\'"',
        '  works far better than asking generally for good copy.',
        '- **Do not invent facts.** Prices, phone numbers, addresses, awards and years',
        '  of founding are claims published on a real business\'s site. An empty field',
        '  the owner fills in is correct; a plausible invented one is not.',
        '',
    );

    return lines.join('\n');
}

if (process.argv[1]?.endsWith('prompt-library.ts')) {
    const out = join(process.cwd(), 'docs/ai/PROMPT_LIBRARY.md');
    writeFileSync(out, buildPromptLibrary());
    console.log(`saved -> ${out}`);
}
