import { writeFileSync } from 'node:fs';
import { TEMPLATES } from '@/lib/templates';

// Generates docs/template-provenance.md — the ledger the licence audit owes (C-06, R2 D18).
//
// Written by a script rather than by hand because a hand-kept ledger of 115 designs is
// out of date the day after it is written, and a stale compliance record is worse than
// none: it is a document that says somebody checked.
//
//   npm run templates:ledger

const rows = TEMPLATES.map((t) => {
    const html = t.files['index.html'] ?? '';
    const photo = /<img[^>]+src="https:\/\/images\.unsplash\.com\/(photo-[^?"]+)/.exec(html)?.[1];
    return { id: t.id, name: t.name, category: t.category, tier: t.tier, license: t.license, photo };
});

const tiers = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.tier] = (acc[r.tier] ?? 0) + 1;
    return acc;
}, {});

const lines = [
    '# Template provenance ledger',
    '',
    `Generated by \`npm run templates:ledger\` from the library itself — do not edit by hand.`,
    '',
    `**${rows.length} designs.** Tiers: ${Object.entries(tiers).map(([k, v]) => `${v} ${k}`).join(', ')}.`,
    `Licences recorded: ${[...new Set(rows.map((r) => r.license))].join(', ')}.`,
    `Designs embedding a photograph: ${rows.filter((r) => r.photo).length}.`,
    '',
    '## Origin',
    '',
    'Every design below is first-party: its blueprint lives in `src/lib/templates/designs.ts`',
    'and the markup, stylesheet and content schema are generated from it. There is no',
    'upstream project to credit, which is why every row names the same source.',
    '',
    'A design sourced from someone else\'s work must record their repository instead. The',
    'normaliser (`npm run templates:normalise`) refuses a source that names neither a licence',
    'nor a URL, so one cannot enter the library without provenance.',
    '',
    '## Photographs',
    '',
    'Hero photographs are served from Unsplash. The Unsplash licence permits use, including',
    'commercially, without attribution — so they ship inside published sites without a credit',
    'requirement. Photographs a site owner adds themselves are a different matter and do carry',
    'attribution into the page footer (S-1).',
    '',
    '## The designs',
    '',
    '| # | Design | Category | Tier | Licence | Hero photograph |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows.map((r, i) =>
        `| ${i + 1} | ${r.name} | ${r.category} | ${r.tier} | ${r.license} | ${r.photo ? `[${r.photo}](https://unsplash.com/photos/${r.photo.replace('photo-', '')})` : '—'} |`),
    '',
];

writeFileSync('docs/template-provenance.md', lines.join('\n'), 'utf8');
console.log(`wrote docs/template-provenance.md — ${rows.length} designs`);
