drop policy if exists project_assets_delete_own on storage.objects;
drop policy if exists project_assets_update_own on storage.objects;
drop policy if exists project_assets_insert_own on storage.objects;
drop policy if exists project_assets_select_own on storage.objects;
delete from storage.buckets where id = 'project-assets';
drop trigger if exists auth_user_profile_updated on auth.users;
drop trigger if exists auth_user_profile_created on auth.users;
drop table if exists public.assets cascade;
drop table if exists public.generations cascade;
drop table if exists public.deployments cascade;
drop table if exists public.commits cascade;
drop table if exists public.project_files cascade;
drop table if exists public.projects cascade;
drop table if exists public.templates cascade;
drop table if exists public.users cascade;
drop function if exists public.enforce_project_asset_limit();
drop function if exists public.enforce_project_file_limits();
drop function if exists public.create_user_profile();
drop function if exists public.set_updated_at();
drop type if exists public.asset_kind;
drop type if exists public.generation_status;
drop type if exists public.deployment_status;
drop type if exists public.template_category;
