-- Rollback for 20260809120000_template_categories.sql
--
-- Postgres cannot drop a value from an enum. Reversing this means rebuilding the type,
-- which is only safe once no row uses any of the added values:
--
--   alter table public.templates alter column category type text;
--   drop type public.template_category;
--   create type public.template_category as enum (
--     'portfolio', 'restaurant', 'saas', 'blog', 'event',
--     'resume', 'agency', 'store', 'nonprofit', 'other'
--   );
--   alter table public.templates
--     alter column category type public.template_category
--     using category::public.template_category;
--
-- Left commented deliberately: running it against a database holding any design in one of
-- the added categories would fail on the final cast, and should. Check first:
--
--   select distinct category from public.templates;
